### ISSUE TITLE
Doesn't seem to work. No output. 

### ISSUE THREAD

**Issue by nitinkgp23** [madan96/La-Z-Boy#1]

**Comment by nitch13jan** [comment]
/home/nitin/Pictures/Screenshot from 2016-08-18 08-20-18.png

**Comment by nitinkgp23** [comment]
![screenshot from 2016-08-18 08-20-18](https://cloud.githubusercontent.com/assets/16208882/17760496/c514a3e0-651d-11e6-8d2f-025385d56bb1.png)

**Comment by nitinkgp23** [comment]
No data in `movie_name`  (Line 34)

The html object stored in req.read() doesn't contain the required part.

`<div class="col-lg-8 col-md-12 col-sm-12"> <div class="shows-box">
                        <h2>Star Movies</h2>
                        
                        <div>
                            <div class="row">
                                <div class="clearfix"></div>
                            </div>
                        </div>
                    </div>
                </div>`

**Comment by madan96** [comment]
Don't add a '-' between movie names. Simply write `python main.py star
movies`



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=rishabhmadan96@gmail.com&idSignature=22>

**Comment by madan96** [comment]
I just tried running the script and it seems to work fine for me. 
![screenshot from 2016-08-18 10 54 04](https://cloud.githubusercontent.com/assets/13871064/17762885/1da6f616-6532-11e6-9055-420e5ef0f9dd.png)

Did you enter the channel name without '-' in between?
