### ISSUE TITLE
Create a Recommendation system

### ISSUE THREAD

**Issue by madan96** [madan96/La-Z-Boy#18]
The user would select some Genre, and the program will recommend 5 of the best movies/tv-series-episode of that genre showing up on the TV that day.

**Comment by MandarMK** [comment]
My last PR (b188af4917c3fb2c13bbe39468857cab31f821db)  fixes #18
I have added recommendation system that takes in genre and give 5 highest rated movies.

**Comment by madan96** [comment]
#30 fixes this for now.
