### ISSUE TITLE
Integrate database for storing scraping data

### ISSUE THREAD

**Issue by madan96** [madan96/La-Z-Boy#19]
For all the ideas that we will be working on. would require a database of all the scraped data. It will therefore be very important to have the data stored in a database.

**Comment by arsalansaad** [comment]
@madan96 does the scraping data include name and imdb rating of the movies or anything else?

**Comment by madan96** [comment]
It includes name, rating and time of broadcast.

**Comment by arsalansaad** [comment]
@madan96  not the channel?

**Comment by madan96** [comment]
Channel is given as the input.

**Comment by madan96** [comment]
@arsalansaad For this database part, we would require a different script that would scrape data from a set of movie/entertainment channels and feed them into the table.

**Comment by arsalansaad** [comment]
@madan96 not the channels that are currently supported?

**Comment by madan96** [comment]
@arsalansaad There have been some changes recently. The script now supports many more channels. Please view the code for further information.

**Comment by arsalansaad** [comment]
i have sent a pr regarding the same
