### ISSUE TITLE
Add Pretty print functionality

### ISSUE THREAD

**Issue by madan96** [madan96/La-Z-Boy#2]
Use Python pretty print for showcasing the output after scraping.

**Comment by Evalle** [comment]
Hello @madan96 can I work on this one ?

**Comment by madan96** [comment]
Definitely! Go for it.

**Comment by Evalle** [comment]
Hello @HackToHell can you please comment that you're working on the issue before creating PR ? It's win-win behavior for everyone. 
@madan96 are you OK with this PR? Should I continue to work on this issue ?

**Comment by madan96** [comment]
@Evalle You can continue to work on this PR. Just remember that the table contains both row and column lines.

**Comment by Evalle** [comment]
@madan96 got it.

**Comment by HackToHell** [comment]
@Evalle Sure, considering the program didn't output a lot of data, figured a bare minimum ASCII table would do the trick.
