### ISSUE TITLE
Edit README.md

### ISSUE THREAD

**Issue by madan96** [madan96/La-Z-Boy#25]
Since this project has been converted from a single script to a Python package. README needs to be updated regarding running it.

**Comment by swapnil-ss** [comment]
@madan96  what is the name of the package so that we can update the README ??

**Comment by madan96** [comment]
It's La-Z-Boy. You can check `setup.py` file to confirm the package name.

**Comment by AnandKumar22** [comment]
I have also added BeautifulSoup4 in setup.py under the section of install_requires.....
