### ISSUE TITLE
Add provision to save output as PDF

### ISSUE THREAD

**Issue by madan96** [madan96/La-Z-Boy#3]
Ask the user if he wants to save the result as PDF `Y/N`. If yes, save it as PDF.

**Comment by MohamedWasim** [comment]
Firstly, create a print-specific style sheet:

<link type="text/css" media="screen" rel="stylesheet" href="/css/main.css">
<link type="text/css" media="print" rel="stylesheet" href="/css/print.css">

Then copy and paste the main styles and change any sections you don't want to print as display:none. Alter other styles to suit.

There are many other nice things you can do on a print style sheet, like print URLs after a link. Here are some useful references:

http://www.alistapart.com/articles/goingtoprint/521
http://www.koodoz.com.au/klog/web-design-html-xhtml-css-cascading-style-sheets-hyper-text-markup-language-javascript-flash-php/working-with-print-style-sheets-an-introduction/201
http://evolt.org/node/2222559
http://www.webcredible.co.uk/user-friendly-resources/css/print-stylesheet.shtml108
http://davidwalsh.name/optimizing-structure-print-css118
http://davidwalsh.name/optimizing-content-print-css99
http://davidwalsh.name/css-page-breaks82
http://net.tutsplus.com/tutorials/html-css-techniques/10-challenging-but-awesome-css-techniques/100
(item 9)

**Comment by prashant2018** [comment]
@madan96 Hi, I would like to take this.

**Comment by madan96** [comment]
Go for it.

**Comment by prashant2018** [comment]
check pull request #8
